version: '3'

services:
  frontend:
    image: frontend
    build: ./frontend
    restart: always
    ports:
      - "8888:3000"

  backend:
    image: backend
    build: ./backend
    restart: always
    ports:
      - 4567:4567
