version: '3'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      args:
        backend_url: https://explorer.raiden.network/json
        poll_interval: 10000
        etherscan_base_url: https://ropsten.etherscan.io/address/
        echo_node_address: "0x02f4b6BC65561A792836212Ebc54434Db0Ab759a"
        network_type: ""
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network"

  backend:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.ropsten.ethnodes.brainbot.com:8545
      - EXPLORER_REGISTRY_ADDRESS=0xf2a175A52Bd3c815eD7500c765bA19652AB89B30
      - EXPLORER_START_BLOCK=3800000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network; Path: /json"

  frontend-ropsten:
    image: frontend
    build:
      context: ./frontend
      args:
        backend_url: https://ropsten.explorer.raiden.network/json
        poll_interval: 10000
        etherscan_base_url: https://ropsten.etherscan.io/address/
        echo_node_address: "0x02f4b6BC65561A792836212Ebc54434Db0Ab759a"
        network_type: Ropsten
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ropsten.explorer.raiden.network"

  backend-ropsten:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.ropsten.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ropsten.explorer.raiden.network; Path: /json"

  frontend-rinkeby:
    image: frontend
    build:
      context: ./frontend
      args:
        backend_url: https://rinkeby.explorer.raiden.network/json
        poll_interval: 10000
        etherscan_base_url: https://rinkeby.etherscan.io/address/
        network_name: Rinkeby
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rinkeby.explorer.raiden.network"

  backend-rinkeby:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.rinkeby.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rinkeby.explorer.raiden.network; Path: /json"

  frontend-kovan:
    image: frontend
    build:
      context: ./frontend
      args:
        backend_url: https://kovan.explorer.raiden.network/json
        poll_interval: 10000
        etherscan_base_url: https://kovan.etherscan.io/address/
        network_name: Kovan
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kovan.explorer.raiden.network"

  backend-kovan:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://parity.kovan.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kovan.explorer.raiden.network; Path: /json"

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik:/etc/traefik
      - ./data/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
      - backend-ropsten
      - backend-rinkeby
      - backend-kovan
      - frontend
      - frontend-ropsten
      - frontend-rinkeby
      - frontend-kovan
