version: '3'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network"

  backend:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.ropsten.ethnodes.brainbot.com:8545
      - EXPLORER_REGISTRY_ADDRESS=0xf2a175A52Bd3c815eD7500c765bA19652AB89B30
      - EXPLORER_START_BLOCK=3800000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network; Path: /json"

  backend-ropsten:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.ropsten.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ropsten.explorer.raiden.network; Path: /json"

  backend-rinkeby:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.rinkeby.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rinkeby.explorer.raiden.network; Path: /json"

  backend-kovan:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://parity.kovan.ethnodes.brainbot.com:8545
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kovan.explorer.raiden.network; Path: /json"

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik:/etc/traefik
      - ./data/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
      - backend-ropsten
      - backend-rinkeby
      - backend-kovan
      - frontend
