version: '3'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network"
      - "traefik.port=3000"

  backend:
    image: backend
    build:
      context: ./backend
    restart: always
    environment:
      - EXPLORER_ETH_RPC=http://geth.ropsten.ethnodes.brainbot.com:8545
      - EXPLORER_REGISTRY_ADDRESS=0xf2a175A52Bd3c815eD7500c765bA19652AB89B30
      - EXPLORER_START_BLOCK=3800000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:explorer.raiden.network; Path: /json"
      - "traefik.port=4567"

  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik:/etc/traefik
      - ./data/traefik:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
      - frontend
